name: ci-ubuntu

on: [pull_request, workflow_dispatch]

jobs:
    ci-ubuntu-20-04-gplusplus:
        name: ci-ubuntu-20.04-g++-${{ matrix.gplusplus_version }}
        runs-on: ubuntu-latest
        container:
            image: ubuntu:20.04
            env:
                TZ: America/New_York
                DEBIAN_FRONTEND: noninteractive
        services:
            nginx:
                image: nginx:stable
            haproxy:
                image: jbaldwindh/liblifthttp-automation-haproxy:0.1
        strategy:
            matrix:
                gplusplus_version: [9]
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: apt
                run: |
                    apt-get update
                    apt-get -y upgrade
                    apt install -y build-essential software-properties-common
                    add-apt-repository ppa:ubuntu-toolchain-r/test
                    apt-get install -y \
                        cmake \
                        git \
                        ninja-build \
                        g++-${{ matrix.gplusplus_version }} \
                        zlib1g-dev \
                        libcurl4-openssl-dev \
                        libuv1-dev \
                        curl
            -   name: check-haproxy
                run: |
                    curl -v --user guest:guestpassword -x "http://haproxy:3128" "http://nginx/index.html"
            -   name: build-release-g++
                run: |
                    mkdir build-release-g++
                    cd build-release-g++
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=gcc-${{ matrix.gplusplus_version }} \
                        -DCMAKE_CXX_COMPILER=g++-${{ matrix.gplusplus_version }} \
                        ..
                    ninja
            -   name: test-release-g++
                run: |
                    cd build-release-g++
                    ctest -VV

    ci-ubuntu-20-04-clang:
        name: ci-ubuntu-20.04-clang-${{ matrix.clang_version }}
        runs-on: ubuntu-latest
        container:
            image: ubuntu:20.04
            env:
                TZ: America/New_York
                DEBIAN_FRONTEND: noninteractive
        services:
            nginx:
                image: nginx:stable
            haproxy:
                image: jbaldwindh/liblifthttp-automation-haproxy:0.1
        strategy:
            matrix:
                clang_version: [9]
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: apt
                run: |
                    apt-get update
                    apt-get -y upgrade
                    apt install -y build-essential software-properties-common
                    add-apt-repository ppa:ubuntu-toolchain-r/test
                    apt-get install -y \
                        cmake \
                        git \
                        ninja-build \
                        clang-${{ matrix.clang_version }} \
                        zlib1g-dev \
                        libcurl4-openssl-dev \
                        libuv1-dev \
                        curl
            -   name: check-haproxy
                run: |
                    curl -v --user guest:guestpassword -x "http://haproxy:3128" "http://nginx/index.html"
            -   name: build-release-clang
                run: |
                    mkdir build-release-clang
                    cd build-release-clang
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=clang-${{ matrix.clang_version }} \
                        -DCMAKE_CXX_COMPILER=clang++-${{ matrix.clang_version }} \
                        ..
                    ninja
            -   name: test-release-clang
                run: |
                    cd build-release-clang
                    ctest -VV

    ci-ubuntu-22-04-gplusplus-clang:
        name: ci-ubuntu-22.04-g++
        runs-on: ubuntu-latest
        container:
            image: ubuntu:22.04
            env:
                TZ: America/New_York
                DEBIAN_FRONTEND: noninteractive
        services:
            nginx:
                image: nginx:stable
            haproxy:
                image: jbaldwindh/liblifthttp-automation-haproxy:0.1
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: apt
                run: |
                    apt-get update
                    apt-get -y upgrade
                    apt install -y build-essential software-properties-common
                    apt-get install -y \
                        cmake \
                        git \
                        ninja-build \
                        g++ \
                        clang \
                        zlib1g-dev \
                        libssl-dev \
                        libuv1-dev \
                        curl \
                        wget
            -   name: check-haproxy
                run: |
                    curl --user guest:guestpassword -x "http://haproxy:3128" "http://nginx/index.html"
            -   name: build-libcurl
                run: |
                    # We have to custom build libcurl because ubuntu 22.02 default comes with a broken
                    # libcurl verison 7.81.0 that has a mutli interface segfault.
                    # See:
                    #   https://github.com/jbaldwin/liblifthttp/issues/142
                    wget https://github.com/curl/curl/releases/download/curl-7_86_0/curl-7.86.0.tar.gz
                    gunzip curl-7.86.0.tar.gz
                    tar -xf curl-7.86.0.tar
                    cd curl-7.86.0/
                    ./configure --with-openssl
                    make -j $(nproc)
                    make install
            -   name: build-release-g++
                run: |
                    mkdir build-release-g++
                    cd build-release-g++
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=gcc \
                        -DCMAKE_CXX_COMPILER=g++ \
                        -DLIFT_USER_LINK_LIBRARIES="/usr/local/lib/libcurl.so.4;z;uv;pthread;dl;stdc++fs" \
                        ..
                    ninja
            -   name: build-release-clang
                run: |
                    mkdir build-release-clang
                    cd build-release-clang
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=clang \
                        -DCMAKE_CXX_COMPILER=clang++ \
                        -DLIFT_USER_LINK_LIBRARIES="/usr/local/lib/libcurl.so.4;z;uv;pthread;dl;stdc++fs" \
                        ..
                    ninja
            -   name: test-release-g++
                run: |
                    cd build-release-g++
                    ctest -VV
            -   name: test-release-clang
                run: |
                    cd build-release-clang
                    ctest -VV

    ci-ubuntu-24-04-gplusplus:
        name: ci-ubuntu-24.04-g++-${{ matrix.gplusplus_version }}
        runs-on: ubuntu-latest
        container:
            image: ubuntu:24.04
            env:
                TZ: America/New_York
                DEBIAN_FRONTEND: noninteractive
        services:
            nginx:
                image: nginx:stable
            haproxy:
                image: jbaldwindh/liblifthttp-automation-haproxy:0.1
        strategy:
            matrix:
                gplusplus_version: [10, 11, 12, 13, 14]
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: apt
                run: |
                    apt-get update
                    apt-get -y upgrade
                    apt install -y build-essential software-properties-common
                    add-apt-repository ppa:ubuntu-toolchain-r/test
                    apt-get install -y \
                        cmake \
                        git \
                        ninja-build \
                        g++-${{ matrix.gplusplus_version }} \
                        zlib1g-dev \
                        libcurl4-openssl-dev \
                        libuv1-dev \
                        curl
            -   name: check-haproxy
                run: |
                    curl -v --user guest:guestpassword -x "http://haproxy:3128" "http://nginx/index.html"
            -   name: build-release-g++
                run: |
                    mkdir build-release-g++
                    cd build-release-g++
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=gcc-${{ matrix.gplusplus_version }} \
                        -DCMAKE_CXX_COMPILER=g++-${{ matrix.gplusplus_version }} \
                        ..
                    ninja
            -   name: test-release-g++
                run: |
                    cd build-release-g++
                    ctest -VV

    ci-ubuntu-24-04-clang:
        name: ci-ubuntu-24.04-clang-${{ matrix.clang_version }}
        runs-on: ubuntu-latest
        container:
            image: ubuntu:24.04
            env:
                TZ: America/New_York
                DEBIAN_FRONTEND: noninteractive
        services:
            nginx:
                image: nginx:stable
            haproxy:
                image: jbaldwindh/liblifthttp-automation-haproxy:0.1
        strategy:
            matrix:
                clang_version: [14, 15, 16, 17, 18, 19]
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: apt
                run: |
                    apt-get update
                    apt-get -y upgrade
                    apt install -y build-essential software-properties-common
                    add-apt-repository ppa:ubuntu-toolchain-r/test
                    apt-get install -y \
                        cmake \
                        git \
                        ninja-build \
                        clang-${{ matrix.clang_version }} \
                        zlib1g-dev \
                        libcurl4-openssl-dev \
                        libuv1-dev \
                        curl
            -   name: check-haproxy
                run: |
                    curl -v --user guest:guestpassword -x "http://haproxy:3128" "http://nginx/index.html"
            -   name: build-release-clang
                run: |
                    mkdir build-release-clang
                    cd build-release-clang
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=clang-${{ matrix.clang_version }} \
                        -DCMAKE_CXX_COMPILER=clang++-${{ matrix.clang_version }} \
                        ..
                    ninja
            -   name: test-release-clang
                run: |
                    cd build-release-clang
                    ctest -VV
