name: ci-windows

on: [pull_request, workflow_dispatch]

jobs:
    ci-windows-2025:
        name: windows-2025
        runs-on: windows-2025
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Install Dependencies
                run: |
                    vcpkg install curl:x64-windows
                    vcpkg install libuv
            -   name: Build
                run: |
                    mkdir Release
                    cd Release
                    cmake -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake -DLIFT_BUILD_EXAMPLES=OFF ..
                    cmake --build . --config Release
            -   name: Test
                run: |
                    cd Release
                    ctest --build-config Release -VV
